### ISSUE TITLE
Incorrect Rate Icon

### ISSUE THREAD

**Issue by zipatton** [Minemaker0430/GDDPIntegration#10]
## When going to someone's account from one of the GDDP lists, all of their levels show as whatever list you were in.

<details>
<summary> Images </summary>

![20240314122327_1](https://github.com/Minemaker0430/GDDPIntegration/assets/155669622/62c78e23-220f-4202-ac1c-36dc8f95b908)

![20240314122333_1](https://github.com/Minemaker0430/GDDPIntegration/assets/155669622/bbb8b49d-4260-47b4-abdc-c2129a90378d)

> Current Version: v1.0.0-BETA.10

</details>

**Comment by Minemaker0430** [comment]
Known issue, will be fixed in the future

**Comment by Minemaker0430** [comment]
fixed in beta 11
