### ISSUE TITLE
GDDP Integration Crash

### ISSUE THREAD

**Issue by Bicaizans** [Minemaker0430/GDDPIntegration#24]
So i got different mods installed and one of them is the GDDP Integration mod. I use the website but I would love to use this in-game. When i click on progression and then on "view" on any demon pack, my game crashes. Any help?
![crashlogGD](https://github.com/Minemaker0430/GDDPIntegration/assets/173795034/0fe2ed52-2be7-404f-bfac-136ccf25b967)

**Comment by Minemaker0430** [comment]
Currently trying to work on a solution, since I've gotten other reports of the mod crashing like this. Sorry you're having issues with the mod

**Comment by Bicaizans** [comment]
No worries, take your time.

**Comment by Minemaker0430** [comment]
Can you download the latest version and see if it crashes?
https://github.com/Minemaker0430/GDDPIntegration/releases/tag/v1-beta.27

**Comment by Bicaizans** [comment]
It does work thank you so much!
