### ISSUE TITLE
Lists now look unconventional and inconvenient to surf

### ISSUE THREAD

**Issue by TeahersAreStupid1234** [Minemaker0430/GDDPIntegration#25]
https://i.imgur.com/Fbf9lpo.png

I miss the old list format. Also it now shows the incorrect number of demons beaten (I have 6 it shows 10.)

**Comment by TeahersAreStupid1234** [comment]
https://i.imgur.com/DM7aSBo.png

This looks far better, and also shows the correct number of demons beaten.

**Comment by Minemaker0430** [comment]
I miss the old list format too, however the new lists don't crash and don't refuse to save progress like they used to. The new system is easier to work with despite it not looking aesthetically pleasing, so there's not much I can do unfortunately.
As for the progress bar showing the incorrect amount of levels, not sure how that managed to happen. Any level on a list that's in the GDDP gets registered as completed if you completed it, so maybe something happened there, I'm not sure

**Comment by Aproxia-dev** [comment]
I fixed this using the Compact Lists mod by Cvolton. The only thing that's broken this way are the skillset badges. Perhaps adding compatibility for that mod by just detecting whether it's on and then changing the skillset badges' location might work?

**Comment by Minemaker0430** [comment]
added compatibility for compact lists
