### ISSUE TITLE
Legacy demons beaten prior to being moved to legacy should still count towards non-plus ranks

### ISSUE THREAD

**Issue by Aproxia-dev** [Minemaker0430/GDDPIntegration#27]
I've beaten several platinum tier demons that were later moved to legacy, and as a result I am no longer meeting the requirement for the platinum rank. However I still have platinum rank on the GDDP website.

After further investigation I found out that this is intended behavior, yet the mod seems to not have this integrated, or at least I'm unaware of any way to get the rank with legacy demons retroactively, as I am locked out of sapphire tier in the game. I was wondering whether this could somehow be fixed.

My idea for how it might be fixed is just simply making legacy levels accessible with the main tier unlocked and adding a checkmark next to all your completed legacy levels, which would essentially tell the game "I've beaten this level before it was moved to legacy" and let you claim your rank that way.

You could also add compatibility with BetterInfo, as if the mod was installed during completion, you can see when you've completed a level. This data could be used to automatically check whether a legacy demon was beaten prior to being moved to legacy.

**Comment by Minemaker0430** [comment]
i made it a while back so that rank progress stays even if a level is moved to legacy so you can still get the rank (this doesn't apply for completion ranks)
