### ISSUE TITLE
Gddp crashes when loading the lists

### ISSUE THREAD

**Issue by Elzodracsito2GD** [Minemaker0430/GDDPIntegration#28]
[Crash 2024-07-04 12.06.01.dmp](https://github.com/user-attachments/files/16101195/Crash.2024-07-04.12.06.01.dmp)
When I try to enter progression and it starts loading, it suddenly crashes, I don't know why it happens, yesterday the gddp was working normally, but now it crashes

**Comment by Minemaker0430** [comment]
https://api.geode-sdk.org/v1/mods/minemaker0430.gddp_integration/versions/1.0.0-beta.32/download does this update fix it?
