### ISSUE TITLE
GDDP integration mod in GD crashes when going to monthly section

### ISSUE THREAD

**Issue by MrEmpyreanite** [Minemaker0430/GDDPIntegration#29]
I got this crash report when trying to go into the monthly section of the GDDP integration mod:

2024-07-07T15:12:14-0400
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "minemaker0430.gddp_integration" mod. Please submit this crash report to its developers (Minemaker0430) for assistance.

== Geode Information ==
Loader Version: v3.2.0
Loader Commit: 65ed0d4
Bindings Commit: 103fbd9
Installed mods: 10
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\minemaker0430.gddp_integration\minemaker0430.gddp_integration.dll
Faulty Mod: GDDP Integration v1.0.0-beta.32 (minemaker0430.gddp_integration)
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FFDA95467FA (minemaker0430.gddp_integration.dll + 467fa)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\minemaker0430.gddp_integration\minemaker0430.gddp_integration.dll + 467fa
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\minemaker0430.gddp_integration\minemaker0430.gddp_integration.dll + 4463f
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 597cf (cocos2d::CCMenuItem::activate + 47)
 - 0000028C98C40872 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 3bd65 (geode::modifier::AsStaticFunction_activate<hook7<(anonymous namespace)::hook7Parent>,void (hook7<(anonymous namespace)::hook7Parent>::*)()>::Impl<void (hook7<(anonymous namespace)::hook7Parent>::*)()>::function + 21 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenuItem.hpp:35)
 - 0000028C98C40872 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4461f
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 280d8b (CCMenuItemToggler::activate + 59 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/GeneratedSource.cpp:3401)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 58798 (cocos2d::CCMenu::ccTouchEnded + 40)
 - 0000028C98C40C72 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 3c42f (geode::modifier::AsStaticFunction_ccTouchEnded<hook15<(anonymous namespace)::hook15Parent>,void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::Impl<void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::function + 47 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenu.hpp:105)
 - 0000028C98C40C72 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + b0c3c (cocos2d::CCTouchDispatcher::touches + 444)
 - 0000028C98C46472 (Hook handler)
 - 0000028C98C46472 (Hook handler)
 - 0000028C98C46472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 6b131 (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 97)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 76159 (cocos2d::CCEGLView::onGLFWMouseCallBack + 249)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 76186
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + d686b
 - C:\Windows\System32\USER32.dll + 189a1
 - C:\Windows\System32\USER32.dll + 181eb (CallWindowProcW + 139)
 - C:\Windows\SYSTEM32\OPENGL32.dll + 41eb4
 - C:\Windows\System32\USER32.dll + 189a1
 - C:\Windows\System32\USER32.dll + 18461
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + d4198
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72ca6 (cocos2d::CCApplication::run + 1078)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 23a41a (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\Windows\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\Windows\SYSTEM32\ntdll.dll + 5af28 (RtlUserThreadStart + 40)

== Register States ==
RAX: 0000000000000000
RBX: 0000000000000000
RCX: 0000000000000000
RDX: 0000028c95950000
RBP: 0000000000000000
RSP: 000000fa768ffbd0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffde5daaf28
R8:  0000028c958033c0
R9:  0000000000000001
R10: 0000000000000003
R11: 000000fa768fd920
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.0.3] capeling.startpos_switcher
x | [v1.4.7] dankmeme.globed2
x | [v1.6.4] geode.custom-keybinds
x | [v3.2.0] geode.loader
x | [v1.13.1] geode.node-ids
  | [v1.1.3] hiimjustin000.demons_in_between
x | [v1.2.1] itzkiba.better_progression
  | [v1.2.0] itzkiba.grandpa_demon
x | [v1.0.0-beta.32] minemaker0430.gddp_integration
x | [v1.4.6] thesillydoggo.qolmod

**Comment by MrEmpyreanite** [comment]
it actually crashes when going to any section except main
![Screenshot 2024-07-07 153240](https://github.com/Minemaker0430/GDDPIntegration/assets/174963586/cbb1e048-2d3c-42f4-b9a9-177e4af56955)

**Comment by Minemaker0430** [comment]
Can you try this? I'm editing the mod remotely currently so I'm not able to verify if it works or not. Unzip it and put it under `Geometry Dash\geode\mods`

https://github.com/Minemaker0430/GDDPIntegration/actions/runs/9847119460/artifacts/1679599785

**Comment by Minemaker0430** [comment]
https://api.geode-sdk.org/v1/mods/minemaker0430.gddp_integration/versions/1.0.0-beta.33/download should be fixed in beta 33
