### ISSUE TITLE
Rate all Demons option bugged

### ISSUE THREAD

**Issue by Craanky** [Minemaker0430/GDDPIntegration#36]
On some levels, even though they have a gddl rating, it will not show the new faces, also the levels that show the new icons will always show the beginner demon icon when you open them. 
![image](https://github.com/user-attachments/assets/10b35dcd-3b66-4631-9ade-9830856566df)
it shows the icon here
![image](https://github.com/user-attachments/assets/a37afd78-849b-48ea-aa82-d03f5e7fd63c)
but it shows the beginner demon icon here.

and this level has gddl rating but still dont shows the icons. 
![image](https://github.com/user-attachments/assets/4988ef20-a68d-47c6-8cdf-33c3260355ef)

**Comment by Minemaker0430** [comment]
I'm gonna be honest I genuinely have no idea how the first one is happening, I've been trying to fix it for the past 15 minutes and it won't work for me either. The second one is because I use the GDDL spreadsheet instead of the proper API right now.
