### ISSUE TITLE
Crash when deleting a saved online level/leaving its page

### ISSUE THREAD

**Issue by FRBFStudios** [Minemaker0430/GDDPIntegration#37]
The game crashes whenever I try to delete a saved online level or leave its page. Reported it in the Geode discord, they told me it was because of GDDP integration.
Crashlog:
[2024-08-17_17-16-21.txt](https://github.com/user-attachments/files/16645426/2024-08-17_17-16-21.txt)

**Comment by Minemaker0430** [comment]
will try to fix asap

**Comment by Minemaker0430** [comment]
fixed in beta 40
