### ISSUE TITLE
Recommendations list can hold demons from tiers you have not unlocked yet

### ISSUE THREAD

**Issue by EpsilonTheDerg** [Minemaker0430/GDDPIntegration#40]
Title says it all. Under certain circumstances, the Recommendations list can suggest levels that you technically shouldn't have access to yet in GDDP.
Here, I have nothing but Bronze demons to throw myself at...
![Screenshot from 2024-09-05 17-37-10](https://github.com/user-attachments/assets/8733cce8-9d18-4b60-86a0-289912380929)
...but the Recommendations list is handing me Silver demons.
![Screenshot from 2024-09-05 17-36-51](https://github.com/user-attachments/assets/d73adfec-89ba-4316-ba16-a78e53db16ef)
I doubt this will actually get fixed, considering you can just go beat those levels anyway since GDDP isn't locking you out of anything, but I still thought it was worth bringing up on the off-chance it's unintentional.

**Comment by Minemaker0430** [comment]
Yea this is intended behavior. My guess is it couldn't find any good bronze recommendations so it went to silver.
