### ISSUE TITLE
Startpos level button missing

### ISSUE THREAD

**Issue by Jon17S** [Minemaker0430/GDDPIntegration#43]
Hiya, not sure if you're aware or it's something on my end, but bronze demons are missing the startpos button 
![image](https://github.com/user-attachments/assets/cc0af9d7-af83-41fd-9a29-bbccd1ea1f9c)

Thank you for the cool mod:)

**Comment by Minemaker0430** [comment]
Intended

The sets of startpos levels are ones approved by the gddp staff. Bronze doesn't have a full set of approved bronze startpos levels (that I'm aware of) to go with it, so it's exempt. A few other tiers also have this.

I'm glad you like the mod :)

**Comment by Jon17S** [comment]
Ah makes sense, thanks for getting back to me so quickly!

Jon

On 15 Oct 2024, at 03:51, Minemaker0430 ***@***.***> wrote:

﻿

Intended

The sets of startpos levels are ones approved by the gddp staff. Bronze doesn't have a full set of approved bronze startpos levels (that I'm aware of) to go with it, so it's exempt. A few other tiers also have this.

I'm glad you like the mod :)
