### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by QiuiGD** [Minemaker0430/GDDPIntegration#6]
2024-03-04T18:52:24+0100
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "minemaker0430.gddp_integration" mod. Please submit this crash report to its developers (Minemaker0430) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.21
Loader Commit: 06afbb8
Bindings Commit: ff44163
Installed mods: 67
Problems: 0

== Exception Information ==
Faulty Module: C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\geode\unzipped\minemaker0430.gddp_integration\minemaker0430.gddp_integration.dll
Faulty Mod: minemaker0430.gddp_integration
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 7B97DAE7 (minemaker0430.gddp_integration.dll + dae7)
Number Parameters: 2

== Stack Trace ==
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\geode\unzipped\minemaker0430.gddp_integration\minemaker0430.gddp_integration.dll + dae7
 - 01B8064B
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\geode\unzipped\undefined0.gdtweaks\undefined0.gdtweaks.dll + 100f8
 - 01B8064B
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\GeometryDash.exe + 6f47b
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\libcocos2d.dll + ad27d (cocos2d::CCMenu::ccTouchEnded + 29)
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\libcocos2d.dll + f8df9 (cocos2d::CCTouchDispatcher::touchesEnded + 25)
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\libcocos2d.dll + be92c (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 92)
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\libcocos2d.dll + c7922 (cocos2d::CCEGLView::onGLFWMouseCallBack + 210)
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\libcocos2d.dll + c794e (cocos2d::CCEGLView::onGLFWMouseCallBack + 254)
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\libcocos2d.dll + 116cc9 (cocos2d::CCPoint::unrotate + 8073)
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\libcocos2d.dll + 118819 (cocos2d::CCPoint::unrotate + 15065)
 - C:\Windows\System32\USER32.dll + 4139b (AddClipboardFormatListener + 75)
 - C:\Windows\System32\USER32.dll + 37b3a (GetClassLongW + 1962)
 - C:\Windows\System32\USER32.dll + 372f6 (GetSystemMetricsForDpi + 3142)
 - C:\Windows\System32\USER32.dll + 35aeb (CallWindowProcW + 27)
 - C:\Windows\SYSTEM32\OPENGL32.dll + 4696f (glDebugEntry + 3631)
 - C:\Windows\System32\USER32.dll + 4139b (AddClipboardFormatListener + 75)
 - C:\Windows\System32\USER32.dll + 37b3a (GetClassLongW + 1962)
 - C:\Windows\System32\USER32.dll + 36471 (DispatchMessageW + 1265)
 - C:\Windows\System32\USER32.dll + 35f90 (DispatchMessageW + 16)
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\libcocos2d.dll + 117472 (cocos2d::CCPoint::unrotate + 10034)
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\libcocos2d.dll + c4dd0 (cocos2d::CCApplication::run + 720)
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\GeometryDash.exe + 3c12d8
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\Geode.dll + 16e444 (crashlog::setupPlatformHandlerPost + 3956)
 - C:\Users\pc\Downloads\Descargar GD\Geometry Dash 2.204 Geode\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c5e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c2e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 00000001
EBX: 00000000
ECX: 26aee778
EDX: 018e0000
EBP: 0099f4e8
ESP: 0099f480
EDI: 00000000
ESI: 0099f480
EIP: 7b97dae7

== Installed Mods ==
x | [v1.0.5] abb2k.backup
x | [v1.1.1] adyagd.godlikefaces
x | [v1.1.3] adyagd.ingamelistmod
x | [v1.1.2] alphalaneous.projectedstars
x | [v1.0.2] arkane.dl-team-icons
x | [v1.6.0] beat.click-sound
x | [v1.0.2] bitz.moregames
x | [v1.0.2] blueblock6.cleanstartpos
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.1.4] capeling.demons_in_garage_2.2
x | [v1.0.5] capeling.gamemode_picker
x | [v1.1.4] capeling.icon_profile_2.2
x | [v1.0.2] capeling.icon_randomizer
x | [v1.0.0] capeling.usable_explorers
x | [v1.0.0] cdc.level_thumbnails
x | [v1.0.1] colon.gold_user_coins
x | [v1.5.1] coopeeo.customname
x | [v1.0.0] creo.color_unlock_hack
x | [v1.0.0] creo.music_unlock_hack
x | [v4.1.2] cvolton.betterinfo
x | [v1.0.0] cvolton.compact_lists
x | [v1.3.0] dankmeme.globed2
x | [v1.5.0] egg.icon_hack
x | [v1.0.1] elnexreal.auto_priority
x | [v1.6.1] elohmrow.death_tracker
x | [v1.3.1] elsai.a_daily_shop
x | [v1.0.3] elsai.copyright_remover_for_main_levels
x | [v2.5.2] fleym.nongd
x | [v1.2.16] gdutilsdevs.gdutils
x | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.21] geode.loader
x | [v1.7.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.4.0] hiimjustin000.integrated_demonlist
x | [v6.3.3] hjfod.betteredit
x | [v1.0.1] hjfod.quick-volume-controls
x | [v1.1.0] itzkiba.grandpa_demon
  | [v1.0.0] itzkiba.id_hyperlinks
x | [v1.2.0] khronophobia.more_settings_button
x | [v1.1.0] khronophobia.shortcuts_menu
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v0.1.5] lexi.visiblecheckpoints
x | [v1.2.0] m336.levelinfo
x | [v1.0.2] mat.run-info
x | [v1.0.0-beta.8] minemaker0430.gddp_integration
x | [v1.1.1] ml5.treasure-checklist
x | [v1.0.2] nytelyte.wave_trail_drag_fix
x | [v1.4.0-beta.1] oatmealine.nlw_integration
  | [v1.1.0] polsk.level_quests
x | [v1.0.0] polsk.pause_settings
  | [v1.0.3] saumondeluxe.rainbow_icon
x | [v1.2.1] shineua.minecraft_splash
x | [v1.0.2] slammy333.save_button
x | [v1.0.5] sofabeddd.colored_icon_kit
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.0.0-beta.5] thesillydoggo.comment_emojis
x | [v1.6.9] thesillydoggo.entersearch
x | [v2.2.4] TheSillyDoggo.GradientPages
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.6.6] tpdea.betterpause-Better
x | [v1.9.0] undefined0.gdtweaks
x | [v1.0.0] uproxide.accupracatt
x | [v1.1.2] uproxide.geodedevelopers
  | [v3.0.0] user95401.profile_image
x | [v1.0.4] weebify.coins_in_pause_menu
x | [v1.0.3] weebify.level_info_in_pause_menu
x | [v1.1.1] weebify.restartbtn

**Comment by Minemaker0430** [comment]
What were you trying to do before it crashed?
