### ISSUE TITLE
Button Placement

### ISSUE THREAD

**Issue by zipatton** [Minemaker0430/GDDPIntegration#7]
The current button doesn't look well. I personally think that making the button be the GDDP Icon and having it be above where the BetterInfo button would be a much better place.

sorry if the wording is bad, i was multitasking stuff

**Comment by Minemaker0430** [comment]
I'll make an option to move it in the future, I personally like where it is and how it looks but I get why some people wouldn't.

**Comment by Minemaker0430** [comment]
![image](https://github.com/Minemaker0430/GDDPIntegration/assets/85040155/cbdcd48b-f65d-4006-95ae-c183c857aaab)

Done! Will be in the next update under the setting Compact Menu Button.
