### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Criscuit** [Minemaker0430/GDDPIntegration#8]
The mod worked fine for like 2 weeks, but suddenly after the update it started crashing my game everytime I go to open the progression menu

**Comment by Criscuit** [comment]
![image](https://github.com/Minemaker0430/GDDPIntegration/assets/162523240/a8561df6-2dd4-4e7a-bbe7-633495629d28)
this is the message i get

**Comment by Minemaker0430** [comment]
was a problem on my end, should be fixed now
